# Generated by Django 3.1.4 on 2020-12-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freearticle',
            name='tier',
            field=models.CharField(choices=[('free', 'FREE'), ('premium', 'PREMIUM')], default='free', editable=False, max_length=7),
        ),
        migrations.AddField(
            model_name='premiumarticle',
            name='tier',
            field=models.CharField(choices=[('free', 'FREE'), ('premium', 'PREMIUM')], default='premium', editable=False, max_length=7),
        ),
    ]
