# Generated by Django 3.1.4 on 2020-12-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20201224_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freearticle',
            name='tier',
            field=models.CharField(choices=[('free', 'FREE'), ('premium', 'PREMIUM')], default='free', editable=False, max_length=7),
        ),
    ]
