# Generated by Django 3.1.4 on 2020-12-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20201224_1525'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
